shared:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || '123asd' %>
  neo4j_host: <%= ENV["NEO4J_HOST"] %>
  neo4j_bolt_port: <%= ENV["NEO4J_BOLT_PORT"] %>
  neo4j_username: <%= ENV["NEO4J_USERNAME"] %>
  neo4j_password: <%= ENV["NEO4J_PASSWORD"] %>

test:
  neo4j_host: <%= ENV["NEO4J_TEST_HOST"] %>
  neo4j_bolt_port: <%= ENV["NEO4J_TEST_BOLT_PORT"] %>
  neo4j_username: <%= ENV["NEO4J_TEST_USERNAME"] %>
  neo4j_password: <%= ENV["NEO4J_TEST_PASSWORD"] %>
