shared:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || '123asd' %>

  # Neo4j
  neo4j_host: <%= ENV["NEO4J_HOST"] %>
  neo4j_bolt_port: <%= ENV["NEO4J_BOLT_PORT"] %>
  neo4j_username: <%= ENV["NEO4J_USERNAME"] %>
  neo4j_password: <%= ENV["NEO4J_PASSWORD"] %>

  # sending emails
  smtp_username: <%= ENV["SMTP_USERNAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>
  # default_url is required for links in email body or in links in controller
  # when url host is not available (for example rails console)
  default_url:
    host: <%= ENV["DEFAULT_URL_HOST"] || (Rails.env.development? ? "localhost" : "example.com") %>
    port: <%= ENV["DEFAULT_URL_PORT"] || (Rails.env.development? ? Rack::Server.new.options[:Port] : 80) %>
  mailer_sender: <%= ENV["MAILER_SENDER"] || "Premesti.se <ajd@premesti.se>" %>
  internal_notification_email: <%= ENV["INTERNAL_NOTIFICATION_EMAIL"] || "ajs@premesti.se" %>

test:
  neo4j_host: <%= ENV["NEO4J_TEST_HOST"] %>
  neo4j_bolt_port: <%= ENV["NEO4J_TEST_BOLT_PORT"] %>
  neo4j_username: <%= ENV["NEO4J_TEST_USERNAME"] %>
  neo4j_password: <%= ENV["NEO4J_TEST_PASSWORD"] %>
